testing = 1
depth = -9999
zx = 250
zy = 170
xx = 290
xy = 140
cx = 330
cy = 110
debugx = 780
debugy = 4
escx = 875
escy = 4
shiftx = 700
shifty = 300
button_scale = 1.6
joy_scale = 1.6
joy_posx = -37
joy_posy = 132
joy_center_x = joy_posx + (59 * joy_scale / 2 - 41 * joy_scale / 2)
joy_center_y = joy_posy + (59 * joy_scale / 2 - 41 * joy_scale / 2)
joy_size = 19.675
back_size = 90
blending = 0.6
pause = 0
section = 0
cool = 1
skinselect = 4
persistent = 1
isoncontroller = 0
reset = 0
shiftlock = 0
debugbutton = 0
if file_exists("touch.ini")
{
    ini_open("touch.ini")
    zx = ini_read_real("CONFIG", "zx", 0)
    zy = ini_read_real("CONFIG", "zy", 0)
    xx = ini_read_real("CONFIG", "xx", 0)
    xy = ini_read_real("CONFIG", "xy", 0)
    cx = ini_read_real("CONFIG", "cx", 0)
    cy = ini_read_real("CONFIG", "cy", 0)
    shiftx = ini_read_real("CONFIG", "shiftx", 0)
    shifty = ini_read_real("CONFIG", "shifty", 0)
    joy_posx = ini_read_real("CONFIG", "joy_posx", 0)
    joy_posy = ini_read_real("CONFIG", "joy_posy", 0)
    button_scale = ini_read_real("CONFIG", "button_scale", 0)
    joy_scale = ini_read_real("CONFIG", "joy_scale", 0)
    blending = ini_read_real("CONFIG", "blending", 0)
    skinselect = ini_read_real("CONFIG", "skin", 0)
    performance = ini_read_real("CONFIG", "musicoff", 0)
    shiftlock = ini_read_real("CONFIG", "shiftlock", 0)
    debugbutton = ini_read_real("CONFIG", "debugbutton", 0)
    ini_close()
}
goback = 0
shiftheld = 0
performance = 0
isdebug = 0
zxplace = zx
zyplace = zy
xxplace = xx
xyplace = xy
cxplace = cx
cyplace = cy
shiftxplace = shiftx
shiftyplace = shifty
joy_posxplace = joy_posx
joy_posyplace = joy_posy
isinoptions = 0
joy_scaleplace = joy_scale
button_scaleplace = button_scale
blendingplace = blending
ateseditv2 = 0
atesreset = 50
startreset = 0
deadzone = 10
joyrange = 120
arrowkeys_area_size = 19.675
arrowkeys_back_area_size = 45
analog_scale = 1.6
analog_posx = -37
analog_posy = 132
analog_center_x = joy_posx + (59 * joy_scale / 2 - 41 * joy_scale / 2)
analog_center_y = joy_posy + (59 * joy_scale / 2 - 41 * joy_scale / 2)
